@c The Python X Library -- concepts
@c $Id: concepts.texi,v 1.2 2001-11-30 09:38:20 petli Exp $
@c
@c Copyright 2000 Peter Liljenberg
@c

@node Basic X Concepts
@chapter Basic X Concepts

Here you might find an intruduction to X concepts sometime in the
future.  For now, I just refer to the introduction parts of the standard
X documentation.  A vast collection of X documentation links can be
found at @uref{http://www.rahul.net/kenton/xsites.html}.
