@c The Python X Library -- concepts
@c $Id: concepts.texi,v 1.1 2000-09-06 01:47:19 petli Exp $
@c
@c Copyright 2000 Peter Liljenberg
@c

@node Basic X Concepts
@chapter Basic X Concepts

Here you might find an intruduction to X concepts sometime in the
future.  For now, I just refer to the introduction parts of the standard
X documentation.

